### ISSUE TITLE
Command helm not correctly installed

### ISSUE THREAD

**Issue by msouvatdy** [ilkilab/agorakube#151]
**Bug description**
When setting the variable install_helm in group_vars/all.yaml, it does not install helm properly and not init helm.
**Variable changed to reproduce this bug**
install_helm: true
init_helm: true

The binaries of helm are staying in /usr/local/bin/linux-amd64/helm instead of /usr/local/bin/helm

**Comment by pierreilki** [comment]
Hi @msouvatdy 
Thx for your feedback !
Helm is properly installed on /usr/local/bin/linux-amd64/helm. Only the "creates" path parameter used to control when helm binary have to be downloaded was wrong. This is now fixed by #153
