### ISSUE TITLE
 Add ARM64 job in Travis-CI

### ISSUE THREAD

**Issue by odidev** [ilkilab/agorakube#218]
**Is your feature request related to a problem? Please describe.**
I have successfully added an arm64 job in Travis-CI.

Commit Link - https://github.com/odidev/agorakube/commit/54e59e9540756192d2b49fa25b0303bcd17da873

Travis Link - https://travis-ci.com/github/odidev/agorakube/builds/190626449

**Describe the solution you'd like**
If the above changes look good and you are interested in adding a job for arm64 in Travis-CI, I can raise a PR.

**Comment by pierreilki** [comment]
Fixed by #219
