### ISSUE TITLE
Force Agorakube to use Ansible version 2.9.X

### ISSUE THREAD

**Issue by pierreilki** [ilkilab/agorakube#220]
Agorakube use modules that only work with Ansible 2.9.X.
To fix this issue, update "setup-deploy.sh" to install Ansible 2.9.X instead of Ansible latest retease.

**Comment by mathieubodin** [comment]
FYI, I met the same issue on debian buster (10): the ansible stable version on this OS (10.0.6) is **2.7.7+dfsg-1**.

**Comment by pierreilki** [comment]
This PR as been fixed

Agorakube use by default Ansible 2.9.X with Centos7 and Python2
Agorakube use by default Ansible 2.10.X with Python3 and others OS
