### ISSUE TITLE
The variable "delete_previous_k8s_install" does not apply on workers

### ISSUE THREAD

**Issue by mathieubodin** [ilkilab/agorakube#221]
**Describe the bug**
Switching variable `kubernetes_release` from one version to another does not apply on workers, despite setting `delete_previous_k8s_install` to `True`. 

**To Reproduce**
1. Configure `group_vars/all.yaml` to use `kubernetes_release` v1.19.3
2. Start deploy as documented, but stop installation process before it ends
3. Reconfigure `group_vars/all.yaml` to use `kubernetes_release` v1.18.8, and `delete_previous_k8s_install` to `True` 
4. Restart deploy as documented
5. Once it try to "Verify if coredns pods has successfully started" (it's a task from "post-scripts" role), check nodes with a command like `kubectl --kubeconfig /var/agorakube/pki/kubeconfigs/admin/admin.conf get nodes`. 

**Expected behavior**
Kubernetes version should be coherent amongs nodes, masters **and** workers.

**Screenshots**

```shell
root@deployment:~# kubectl --kubeconfig /var/agorakube/pki/kubeconfigs/admin/admin.conf get nodes
NAME      STATUS   ROLES    AGE     VERSION
master1   Ready    master   7m52s   v1.18.8
master2   Ready    master   7m53s   v1.18.8
master3   Ready    master   7m52s   v1.18.8
worker1   Ready    worker   6m59s   v1.19.3
worker2   Ready    worker   6m59s   v1.19.3
worker3   Ready    worker   6m59s   v1.19.3
worker4   Ready    worker   6m58s   v1.19.3
worker5   Ready    worker   6m58s   v1.19.3
worker6   Ready    worker   6m58s   v1.19.3
worker7   Ready    worker   6m58s   v1.19.3
```

**Additional context**
Observed on Debian 10.0.6 nodes, ansible 2.9.14.

**Comment by pierreilki** [comment]
Hi @mathieubodin 

I can't reproduce your issue on my environment.
When "delete_previous_k8s_install" is set to "True", all K8S components are deleted from all nodes, then reinstalled.
Does Agorakube runs sucessfully when "ansible-playbook agorakube.yaml ?

If you wanna try Agorakube easilly, you can find some "Vagrantfiles" at https://github.com/ilkilab/agorakube/tree/core/labs
Does Agorakube deployment runs sucessfully ?

**Comment by knowings** [comment]
Hi @pierreilki,

I 'll try with the Vagrantfiles as soon as I find some time ! My cluster is running well after VM snapshots rollbacks, so I won't play with it.

Just need a hint, what should I check to be sure everything is uninstalled ?

To answer you, yes Agorakube runs successfully *in fine*, but as I stated in the reproduction steps, it has failed a first time.

**Comment by pierreilki** [comment]
Hi @knowings 

To be sure that everything is uninstalled:

### On Deployment/Agorakube machine, ensure that :
  - Ansible is not installed
  - Agorakube default data dir "/var/agorakube" is not present

### On ETCD members:
  - ETCD bin dir not present : /usr/bin/etcd-{{ etcd_release }}-linux-amd64
  - ETCD default data dir not present: /var/lib/etcd
  - ETCD service definition not present in /etc/systemd/system/etcd.service

### On K8S masters/workers:
  - Container Engine not present (Docker or Containerd)
  - Kubernetes bin not present (Installed in /usr/local/bin/kubernetes/server/bin/)
  - Kubernetes service definition not present in /etc/systemd/system/kube-*.service + kubelet.service)
  - CNI bin dir not present /opt/cni/bin/
  - If storage as been installed, also remove default persistent data dir "/var/openebs/"

**Comment by knowings** [comment]
Hi @pierreilki 

I think the issue #226 is related to this one.

**Comment by mathieubodin** [comment]
Once again, still impossible to delete previous install of Agorakube... Even with `delete_previous_k8s_install` set to true. This time I tried to change the cluster_cidr, the service_ip_range, the kubernetes_service and the cluster_dns_ip as the IPs collide with internal infrastructure. Don't act, at the time of the first install those IPs were OK.

It seems, it reuse the previous installation, I've got the installation process failing with the following message:

```
fatal: [kubecorp-731.corp.lan]: FAILED! => {"changed": true, "cmd": ["kubectl", "--kubeconfig", "/var/agorakube/pki/kubeconfigs/admin/admin.conf", "apply", "-f", "/tmp/ansible.pfcV7Acoredns/coredns.yaml"], "delta": "0:00:00.275252", "end": "2021-03-23 02:36:34.012778", "msg": "non-zero return code", "rc": 1, "start": "2021-03-23 02:36:33.737526", "stderr": "The Service \"kube-dns\" is invalid: spec.clusterIP: Invalid value: \"172.17.0.10\": field is immutable", "stderr_lines": ["The Service \"kube-dns\" is invalid: spec.clusterIP: Invalid value: \"172.17.0.10\": field is immutable"], "stdout": "serviceaccount/coredns unchanged\nclusterrole.rbac.authorization.k8s.io/system:coredns unchanged\nclusterrolebinding.rbac.authorization.k8s.io/system:coredns unchanged\nconfigmap/coredns configured\ndeployment.apps/coredns unchanged", "stdout_lines": ["serviceaccount/coredns unchanged", "clusterrole.rbac.authorization.k8s.io/system:coredns unchanged", "clusterrolebinding.rbac.authorization.k8s.io/system:coredns unchanged", "configmap/coredns configured", "deployment.apps/coredns unchanged"]}
```

I checked the pods with the command from the message and discover the previous pods are still running... 

Agorakube **need** a procedure for uninstall.
