### ISSUE TITLE
Add support for FQDN in variable "advertise_ip_masters"

### ISSUE THREAD

**Issue by mathieubodin** [ilkilab/agorakube#222]
**Is your feature request related to a problem? Please describe.**
In order to get rid of static IPs within the infrastructure, I wish it would be possible to use FQDN to specify where is the control-plane proxy. For now, the task "generate-certs : Generate CSR for kube-apiserver" fails as it looks for an IPv4 or IPv6 address.

**Describe the solution you'd like**
Allow FQDN to specify where is the control-plane proxy.

**Comment by pierreilki** [comment]
Hi @mathieubodin 

Thank you for your feedback ! This feature is in progress on and will be added soon 👍

**Comment by pierreilki** [comment]
fixed by #225
