### ISSUE TITLE
Updating Kubernetes from v1.18.10 to v1.19.3 breaks the cluster

### ISSUE THREAD

**Issue by Cedric-Caballol-Shepy** [ilkilab/agorakube#226]
**Describe the bug**
The nodes keep being at v1.18.10. 

**Edit:** Actually, the cluster is broken (see the first comment).

**To Reproduce**
1. Have an Agorakube cluster with K8s v1.18.10 working
2. Change the variable `kubernetes_release` to `v1.19.3` in `group_vars/all.yaml`
3. Launch the ansible playbook via `sudo ansible-playbook agorakube.yaml`

**Expected behavior**
`kubectl get nodes` should display nodes in version `1.19.3`

**Additional context**
We're using the Core version. 
We saw that there is a variable `delete_previous_k8s_install`  set to false. We assume that this would kill the cluster to migrate and we don't want that. Is there a documentation somewhere that talks about K8s version migrations ?

**Comment by Cedric-Caballol-Shepy** [comment]
After doing this command `tail -f -n 100 /var/log/messages` on one of the nodes (the first master), we found that `kube-scheduler.service` has not been migrated correctly.
Here are the logs : 

```
Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service holdoff time over, scheduling restart.
Nov 16 15:40:12 kubecorp-731 systemd: Stopped Kubernetes Scheduler v1.19.3.
Nov 16 15:40:12 kubecorp-731 systemd: Started Kubernetes Scheduler v1.19.3.
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.513787   28068 registry.go:150] Registering EvenPodsSpread predicate and priority function
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.514405   28068 registry.go:150] Registering EvenPodsSpread predicate and priority function
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515136   28068 flags.go:33] FLAG: --add-dir-header="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515504   28068 flags.go:33] FLAG: --address="0.0.0.0"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515839   28068 flags.go:33] FLAG: --algorithm-provider=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516179   28068 flags.go:33] FLAG: --alsologtostderr="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516490   28068 flags.go:33] FLAG: --authentication-kubeconfig=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516829   28068 flags.go:33] FLAG: --authentication-skip-lookup="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517146   28068 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517570   28068 flags.go:33] FLAG: --authentication-tolerate-lookup-failure="true"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517885   28068 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518183   28068 flags.go:33] FLAG: --authorization-kubeconfig=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518439   28068 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518685   28068 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518954   28068 flags.go:33] FLAG: --bind-address="127.0.0.1"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519245   28068 flags.go:33] FLAG: --cert-dir=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519533   28068 flags.go:33] FLAG: --client-ca-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519867   28068 flags.go:33] FLAG: --config="/etc/kubernetes/manifests/kube-scheduler.yaml"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520131   28068 flags.go:33] FLAG: --contention-profiling="true"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520480   28068 flags.go:33] FLAG: --feature-gates=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520796   28068 flags.go:33] FLAG: --hard-pod-affinity-symmetric-weight="1"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521102   28068 flags.go:33] FLAG: --help="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521397   28068 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521684   28068 flags.go:33] FLAG: --kube-api-burst="100"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522004   28068 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522267   28068 flags.go:33] FLAG: --kube-api-qps="50"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522560   28068 flags.go:33] FLAG: --kubeconfig=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522855   28068 flags.go:33] FLAG: --leader-elect="true"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523107   28068 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523116   28068 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523119   28068 flags.go:33] FLAG: --leader-elect-resource-lock="endpointsleases"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523123   28068 flags.go:33] FLAG: --leader-elect-resource-name="kube-scheduler"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523126   28068 flags.go:33] FLAG: --leader-elect-resource-namespace="kube-system"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523129   28068 flags.go:33] FLAG: --leader-elect-retry-period="2s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523132   28068 flags.go:33] FLAG: --lock-object-name="kube-scheduler"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523135   28068 flags.go:33] FLAG: --lock-object-namespace="kube-system"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523142   28068 flags.go:33] FLAG: --log-backtrace-at=":0"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523148   28068 flags.go:33] FLAG: --log-dir=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523151   28068 flags.go:33] FLAG: --log-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523154   28068 flags.go:33] FLAG: --log-file-max-size="1800"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523158   28068 flags.go:33] FLAG: --log-flush-frequency="5s"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523161   28068 flags.go:33] FLAG: --logtostderr="true"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523164   28068 flags.go:33] FLAG: --master=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523167   28068 flags.go:33] FLAG: --policy-config-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523170   28068 flags.go:33] FLAG: --policy-configmap=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523172   28068 flags.go:33] FLAG: --policy-configmap-namespace="kube-system"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523175   28068 flags.go:33] FLAG: --port="10251"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523179   28068 flags.go:33] FLAG: --profiling="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523182   28068 flags.go:33] FLAG: --requestheader-allowed-names="[]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523187   28068 flags.go:33] FLAG: --requestheader-client-ca-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523190   28068 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523199   28068 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523203   28068 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523208   28068 flags.go:33] FLAG: --scheduler-name="default-scheduler"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523212   28068 flags.go:33] FLAG: --secure-port="10259"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523214   28068 flags.go:33] FLAG: --show-hidden-metrics-for-version=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523217   28068 flags.go:33] FLAG: --skip-headers="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523220   28068 flags.go:33] FLAG: --skip-log-headers="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523223   28068 flags.go:33] FLAG: --stderrthreshold="2"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523226   28068 flags.go:33] FLAG: --tls-cert-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523229   28068 flags.go:33] FLAG: --tls-cipher-suites="[]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523232   28068 flags.go:33] FLAG: --tls-min-version=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523235   28068 flags.go:33] FLAG: --tls-private-key-file=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523238   28068 flags.go:33] FLAG: --tls-sni-cert-key="[]"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523245   28068 flags.go:33] FLAG: --use-legacy-policy-config="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523248   28068 flags.go:33] FLAG: --v="2"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523251   28068 flags.go:33] FLAG: --version="false"
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523256   28068 flags.go:33] FLAG: --vmodule=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523259   28068 flags.go:33] FLAG: --write-config-to=""
Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.821661   28068 serving.go:313] Generated self-signed cert in-memory
Nov 16 15:40:12 kubecorp-731 kube-scheduler: no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:31"
Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service: main process exited, code=exited, status=1/FAILURE
Nov 16 15:40:12 kubecorp-731 systemd: Unit kube-scheduler.service entered failed state.
Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service failed.
```

**Comment by pierreilki** [comment]
Hi @Cedric-Caballol-Shepy 

Thank you for your feedback !

Lot of things here :)

### Different versions between K8S master & worker after update

> The scheduler errors are gone, but we had to reboot the VMs to make them go to `v1.19.3`... Actually the masters bumped to `v1.19.3` but the workers are still in `v1.18.10` !

This is clearly a bug. I created a PR #227 to force K8S bin to restart when new binaries are downloaded. Let me know.

### How to update K8S with agorakube

> **Additional context**
> We're using the Core version.
> We saw that there is a variable `delete_previous_k8s_install` set to false. We assume that this would kill the cluster to migrate and we don't want that. Is there a documentation somewhere that talks about K8s version migrations ?

You're right, there is no documentation about that topic. I will open an issue to correct that point #228  . To update a K8S cluster you have to setup **delete_previous_k8s_install** to **True**. K8S binaries don't save anything themselves at all. All states are saved in ETCD databases.

So to update K8S with Agorakube
  * Set **delete_previous_k8s_install: True**
  * Set **kubernetes_release: vXX.XX.XX** (New desired release)

### Your Kube-Scheduler "bug"

> After doing this command `tail -f -n 100 /var/log/messages` on one of the nodes (the first master), we found that `kube-scheduler.service` has not been migrated correctly.
> Here are the logs :
> 
> ```
> Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service holdoff time over, scheduling restart.
> Nov 16 15:40:12 kubecorp-731 systemd: Stopped Kubernetes Scheduler v1.19.3.
> Nov 16 15:40:12 kubecorp-731 systemd: Started Kubernetes Scheduler v1.19.3.
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.513787   28068 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.514405   28068 registry.go:150] Registering EvenPodsSpread predicate and priority function
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515136   28068 flags.go:33] FLAG: --add-dir-header="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515504   28068 flags.go:33] FLAG: --address="0.0.0.0"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.515839   28068 flags.go:33] FLAG: --algorithm-provider=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516179   28068 flags.go:33] FLAG: --alsologtostderr="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516490   28068 flags.go:33] FLAG: --authentication-kubeconfig=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.516829   28068 flags.go:33] FLAG: --authentication-skip-lookup="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517146   28068 flags.go:33] FLAG: --authentication-token-webhook-cache-ttl="10s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517570   28068 flags.go:33] FLAG: --authentication-tolerate-lookup-failure="true"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.517885   28068 flags.go:33] FLAG: --authorization-always-allow-paths="[/healthz]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518183   28068 flags.go:33] FLAG: --authorization-kubeconfig=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518439   28068 flags.go:33] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518685   28068 flags.go:33] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.518954   28068 flags.go:33] FLAG: --bind-address="127.0.0.1"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519245   28068 flags.go:33] FLAG: --cert-dir=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519533   28068 flags.go:33] FLAG: --client-ca-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.519867   28068 flags.go:33] FLAG: --config="/etc/kubernetes/manifests/kube-scheduler.yaml"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520131   28068 flags.go:33] FLAG: --contention-profiling="true"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520480   28068 flags.go:33] FLAG: --feature-gates=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.520796   28068 flags.go:33] FLAG: --hard-pod-affinity-symmetric-weight="1"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521102   28068 flags.go:33] FLAG: --help="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521397   28068 flags.go:33] FLAG: --http2-max-streams-per-connection="0"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.521684   28068 flags.go:33] FLAG: --kube-api-burst="100"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522004   28068 flags.go:33] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522267   28068 flags.go:33] FLAG: --kube-api-qps="50"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522560   28068 flags.go:33] FLAG: --kubeconfig=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.522855   28068 flags.go:33] FLAG: --leader-elect="true"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523107   28068 flags.go:33] FLAG: --leader-elect-lease-duration="15s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523116   28068 flags.go:33] FLAG: --leader-elect-renew-deadline="10s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523119   28068 flags.go:33] FLAG: --leader-elect-resource-lock="endpointsleases"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523123   28068 flags.go:33] FLAG: --leader-elect-resource-name="kube-scheduler"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523126   28068 flags.go:33] FLAG: --leader-elect-resource-namespace="kube-system"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523129   28068 flags.go:33] FLAG: --leader-elect-retry-period="2s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523132   28068 flags.go:33] FLAG: --lock-object-name="kube-scheduler"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523135   28068 flags.go:33] FLAG: --lock-object-namespace="kube-system"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523142   28068 flags.go:33] FLAG: --log-backtrace-at=":0"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523148   28068 flags.go:33] FLAG: --log-dir=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523151   28068 flags.go:33] FLAG: --log-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523154   28068 flags.go:33] FLAG: --log-file-max-size="1800"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523158   28068 flags.go:33] FLAG: --log-flush-frequency="5s"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523161   28068 flags.go:33] FLAG: --logtostderr="true"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523164   28068 flags.go:33] FLAG: --master=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523167   28068 flags.go:33] FLAG: --policy-config-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523170   28068 flags.go:33] FLAG: --policy-configmap=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523172   28068 flags.go:33] FLAG: --policy-configmap-namespace="kube-system"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523175   28068 flags.go:33] FLAG: --port="10251"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523179   28068 flags.go:33] FLAG: --profiling="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523182   28068 flags.go:33] FLAG: --requestheader-allowed-names="[]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523187   28068 flags.go:33] FLAG: --requestheader-client-ca-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523190   28068 flags.go:33] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523199   28068 flags.go:33] FLAG: --requestheader-group-headers="[x-remote-group]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523203   28068 flags.go:33] FLAG: --requestheader-username-headers="[x-remote-user]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523208   28068 flags.go:33] FLAG: --scheduler-name="default-scheduler"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523212   28068 flags.go:33] FLAG: --secure-port="10259"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523214   28068 flags.go:33] FLAG: --show-hidden-metrics-for-version=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523217   28068 flags.go:33] FLAG: --skip-headers="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523220   28068 flags.go:33] FLAG: --skip-log-headers="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523223   28068 flags.go:33] FLAG: --stderrthreshold="2"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523226   28068 flags.go:33] FLAG: --tls-cert-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523229   28068 flags.go:33] FLAG: --tls-cipher-suites="[]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523232   28068 flags.go:33] FLAG: --tls-min-version=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523235   28068 flags.go:33] FLAG: --tls-private-key-file=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523238   28068 flags.go:33] FLAG: --tls-sni-cert-key="[]"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523245   28068 flags.go:33] FLAG: --use-legacy-policy-config="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523248   28068 flags.go:33] FLAG: --v="2"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523251   28068 flags.go:33] FLAG: --version="false"
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523256   28068 flags.go:33] FLAG: --vmodule=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.523259   28068 flags.go:33] FLAG: --write-config-to=""
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: I1116 15:40:12.821661   28068 serving.go:313] Generated self-signed cert in-memory
> Nov 16 15:40:12 kubecorp-731 kube-scheduler: no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:31"
> Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service: main process exited, code=exited, status=1/FAILURE
> Nov 16 15:40:12 kubecorp-731 systemd: Unit kube-scheduler.service entered failed state.
> Nov 16 15:40:12 kubecorp-731 systemd: kube-scheduler.service failed.
> ```
> 
> We then tried to launch the Ansible playbook with `delete_previous_k8s_install: True`.

That error was normal and it was due to a miss-match between Kubernetes release binaries V1.18.X and this associated config files for kubernetes v1.19.X (Because  of **delete_previous_k8s_install: False**). It is due to an update of "KubeSchedulerConfiguration" kubernetes resource definition in release v1.19.0 which has been corrected by Agorakube at https://github.com/ilkilab/agorakube/blob/core/roles/setup-master/templates/kube-scheduler.yaml.j2 when v1.19.X support has been added.

### The Difference between "Delete previous Binaries / Download Previous Binaries" in masters and workers.

> We observed that the task "Delete prevous k8s binaries" from [setup-master](https://github.com/ilkilab/agorakube/blob/7cd6c97d379065bf9944f8bbc42bd20e552c1401/roles/setup-master/tasks/clean-previous-k8s-install.yaml#L2) differs with [setup-worker](https://github.com/ilkilab/agorakube/blob/7cd6c97d379065bf9944f8bbc42bd20e552c1401/roles/setup-worker/tasks/clean-previous-k8s-install.yaml#L2): one is using a condition, and not the other.
> 
> Idem for the task "Download Kubernetes node binaries" from [setup-master](https://github.com/ilkilab/agorakube/blob/7cd6c97d379065bf9944f8bbc42bd20e552c1401/roles/setup-master/tasks/setup-master.yaml#L11) differs with [setup-worker](https://github.com/ilkilab/agorakube/blob/7cd6c97d379065bf9944f8bbc42bd20e552c1401/roles/setup-worker/tasks/setup-worker.yaml#L28).

The **Master bin archive** contains all K8S binaries - eg: masters **&** workers binaries. Worker bin dir contains only worker binaries. So if a master is also a worker, "setup-master" update all "master & worker" binaries at the same time and that's why we have to condition the download/deletion of that binaries in "setup-worker" which is used in fact only if a node is just a worker, and not a "master-worker".
