### ISSUE TITLE
[Feature] deploy host cannot be remote

### ISSUE THREAD

**Issue by acjohnson** [ilkilab/agorakube#312]
**Is your feature request related to a problem? Please describe.**
The way Agorakube is currently written, the deploy host must be the same machine that you are running `ansible-playbook` on but with some relatively minor adjustments I believe the deploy host could be located on a remote machine. This would have the advantage of letting you run the `agorakube.yaml` playbook from a remote machine (such as your laptop) and not require you to have all of the components installed needed to generate certificates, etc.

**Describe the solution you'd like**
I'd like to be able to set the deploy host in the inventory to a remote server.

**Describe alternatives you've considered**
I've tried using a VM locally but that is irritating. Also I suppose a docker container could be used to run ansible out of instead which would be nice but seems unnecessary for an ansible project to require docker in order to be ran on a remote deploy host.

**Additional context**
I am currently working on this feature, is this something you would be willing to merge as long as the default behavior is preserved?

**Comment by pierreilki** [comment]
Hi @acjohnson 

I notice you closed your PR.
Why do you don't use a remote "deploy" machine and just connect to it from your computer using SSH ? In that case, Agorakube is installed on deploy machine, and not directly on your computer.
This remote "deploy" machine can be shutdown (directory "/var/agorakube" must be saved if you want to destroy the deploy machine) if you don't use Agorakube.
You will still be able to manage K8S from your computer using "kubeconfig" file. (Default is located on remote deploy machine at "/root/.kube/config)

**Comment by acjohnson** [comment]
The main reason for this feature is that the "deploy" machine and Agorakube cluster have limited connectivity and I am unable to clone our internal repositories... Which means I have to rsync a copy of the agorakube repo which includes customized hosts and secrets that can't be pushed to the public github repo.

**Comment by pierreilki** [comment]
OK. So using SCP-like tools from your local to Deploy/Agorakube is not possible ?
Does Agorakube & K8S machines have access to internet (https://github.com/ilkilab/agorakube/blob/master/docs/instructions.md#network)?

**Comment by acjohnson** [comment]
> OK. So using SCP-like tools from your local to Deploy/Agorakube is ~~not possible~~ not ideal...

Access to the Internet isn't the problem, accessing our local repository with inventory and secrets isn't possible from the "deploy" machine

**Comment by pierreilki** [comment]
OK. So i understand that you don't want to store your secret "host" and "group_vars/all.yaml" on your Github repository and it is totally normal :)

When i use Agorakube, I clone the Agorakube project with default "host" and "group_vars/all.yaml" files, and then i edit manually or using "scp", my own files to the agorakube cloned/wget directory. This can be easily automated with many tools, and of course with ansible itself ! You could for example, create a playbook that clone Agorakube to your Agorakube/Deploy machine, and that inject your local "host" and "group_vars/all.yaml" files directly on the remote deployment machine to setup your remote Agorakube environment. Your local Ansible could also run "ansible-playbook agorakube.yaml" on the remote deployment machine.

If you don't want to store your "host" and "group_vars/all.yaml" files on the remote "deploy/Agorakube" filesystem for any reason, you can mount these files using "tmpfs". (And shutdown the Agorakube machine if Agorakube playbooks are not running continuously).

These are only my first ideas :)

**Comment by acjohnson** [comment]
We're on the same page now, I'm hoping eventually to do it differently since having that additional step of copying hosts and secrets to the deploy host should be unnecessary IMO.
