### ISSUE TITLE
/etc/hosts entries can be added but not removed

### ISSUE THREAD

**Issue by acjohnson** [ilkilab/agorakube#327]
I just ran into this where a decommissioned node continues to persist in the `/etc/hosts` file on all nodes.

The issue is because controlplane -> node communication uses short names to connect to the `kubelet`.

The orphaned host entries then takes prescience over the new entries.

In the below example k8s-storage-4 no longer exists (was decommissioned) and then k8s-node-4 was provisioned using the same (now unused) IP address. This immediately causes x509 errors due to subject name mismatch until the orphaned entry is cleaned up across the entire cluster.

Ideally the `/etc/hosts` entries are synced with the `etc_hosts` inventory group including removed hosts.
```
127.0.0.1	localhost
10.0.0.117 k8s-controlplane-1
10.0.0.118 k8s-controlplane-2
10.0.0.119 k8s-controlplane-3
10.0.0.120 k8s-storage-1
10.0.0.121 k8s-storage-2
10.0.0.122 k8s-storage-3
10.0.0.123 k8s-storage-4
10.0.0.125 k8s-node-1
10.0.0.126 k8s-node-2
10.0.0.127 k8s-node-3
10.0.0.123 k8s-node-4

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by pierreilki** [comment]
Thanks for your add and feedback @acjohnson 
I merged your PR :)

Have a nice day
