### ISSUE TITLE
Add relevant informations at the end of agorakube execution

### ISSUE THREAD

**Issue by pierreilki** [ilkilab/agorakube#35]
Add relevant informations at the end of agorakube execution:
Samples:
* Where find admin kubeconfig
* How to access Kubernetes dashboard

**Comment by s-3ntinel** [comment]
Hi, can i work on this also? @pierreilki can you assign it to me?

**Comment by pierreilki** [comment]
Hi @s-3ntinel 

Thanks for contributing :) Sure you can work on it !

Have a nice day

**Comment by hameedullah** [comment]
@s-3ntinel are you working on it?

**Comment by pierreilki** [comment]
Hi @hameedullah, I think he is not.
