### ISSUE TITLE
Add option for install kubernetes dashboard user with admin privileges

### ISSUE THREAD

**Issue by pierreilki** [ilkilab/agorakube#36]
Add option for install kubernetes dashboard user with admin privileges

**Comment by s-3ntinel** [comment]
Hi, can i work on this? @pierreilki can you assign it to me?

**Comment by pierreilki** [comment]
Hi @s-3ntinel 

You can work on it :)

Thanks for contributing, and have a nice day :)

**Comment by hameedullah** [comment]
@s-3ntinel are you working on it?

**Comment by pierreilki** [comment]
Hi @hameedullah, I think he is not.
