### ISSUE TITLE
Change the way Go is installed

### ISSUE THREAD

**Issue by pierreilki** [ilkilab/agorakube#47]
Today, Go is installed by "apt" package manager.
Install it by "wget" to improve installation speed setup.

**Comment by digikin** [comment]
I am not sure I follow because cant you already use wget to [https://golang.org/dl/](https://golang.org/dl/) website for your specific package?  
or...
Are you wanting this added to part of the How to install directions?

**Comment by pierreilki** [comment]
Thanks you @digikin for contributing. I merged your code to /master.
I close this Issue;

Have a good day :)
