### ISSUE TITLE
Use get_url to download helm installer instead of curl

### ISSUE THREAD

**Issue by hameedullah** [ilkilab/agorakube#76]
**Is your feature request related to a problem? Please describe.**
Currently helm is using curl to download and run the helm installer script, this method inside ansible task is not very ansible friendly and its difficult to figure out where the issue is happening. Because its downloading and running the helm installer script in same task.

**Describe the solution you'd like**
get_url module should be used to download the file and set correct permissions, and then command module can be used to run the installer script.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pierreilki** [comment]
Hi @hameedullah 

I already changed the way Helm is installed a few hours ago using "unarchive" ansible module => https://github.com/ilkilab/agorakube/blob/master/roles/install-helm/tasks/main.yaml

Is that what you wanted ?

Regards

**Comment by hameedullah** [comment]
Yup thats perfect! Thank you!
