### ISSUE TITLE
Containerd should not be installed with docker runtime

### ISSUE THREAD

**Issue by hameedullah** [ilkilab/agorakube#77]
**Describe the bug**
Containerd is getting installed when trying to use docker runtime.

**To Reproduce**
1. Edit group_vars/all.yaml
2. Change runtime to 'docker'
3. Deploy agorakube
4. Containerd will be installed along with docker

**Expected behavior**
As per kubernetes documentation containerd is not needed for docker runtime.

**Comment by pierreilki** [comment]
Hi @hameedullah 

Thank you for your feedback ! We will work on it soon. I assign @msouvatdy to solve this issue.

Have a nice day

**Comment by pierreilki** [comment]
Fixed by #89
