### ISSUE TITLE
Add in the doc an array that explain what params we can use in Agorakube

### ISSUE THREAD

**Issue by pierreilki** [ilkilab/agorakube#84]
**Describe the solution you'd like**
Add in the doc an array that explain what params we can use in Agorakube

**Additional context**
Today, Agorakube doesn't have a clear array that match all possible parameters with their definition and  teir possible values (with defaults). Please add this to the docummentation (README.md and docs/instructions.md) to make Agorakube customization easier.

**Comment by ur2p0** [comment]
I take care of this !
